# Generated by Django 2.0 on 2020-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='url',
            field=models.CharField(default='', max_length=30),
        ),
    ]
