# Generated by Django 2.0 on 2020-12-24 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='url',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten letras y números.')]),
        ),
    ]
