# Generated by Django 2.0 on 2020-12-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20201224_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='url',
            new_name='link',
        ),
    ]
