# Generated by Django 2.0 on 2020-12-24 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20201224_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='link',
            field=models.CharField(default='', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten letras y números.')]),
        ),
    ]
