# Generated by Django 2.0 on 2021-01-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='double_authentication',
        ),
        migrations.AddField(
            model_name='extra',
            name='totp_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo 2fa por tiempo'),
        ),
    ]
